#!/usr/bin/env python3
"""Create a production-ready ``.env`` for public deployment.

Writes secrets, sets APP_ENV=production, aligns CORS with SITE_DOMAIN, and leaves
provider keys for you to paste (or pass on the command line).

Examples:
    python scripts/setup_production_env.py --domain app.example.com --email ops@example.com
    python scripts/setup_production_env.py --domain app.example.com --email ops@example.com \\
        --groq-key gsk_... --cohere-key ... --out .env --force

Then on the server (DNS A record → this host, ports 80/443 open):
    python scripts/verify_production_env.py
    docker compose up -d --build
    docker compose --profile tools up -d worker
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _token(nbytes: int = 32) -> str:
    return secrets.token_urlsafe(nbytes)


def build_env_text(
    *,
    domain: str,
    email: str,
    groq_key: str,
    cohere_key: str,
    saas_signup: bool,
    postgres_password: str,
) -> str:
    domain = domain.strip().lower().removeprefix("https://").removeprefix("http://").strip("/")
    cors = f"https://{domain}"
    signup = "true" if saas_signup else "false"
    allow_signup = "true" if saas_signup else "false"
    jwt = _token(48)
    admin = _token(32)

    lines = [
        "# Generated by scripts/setup_production_env.py — do not commit.",
        "APP_ENV=production",
        f"SITE_DOMAIN={domain}",
        f"CADDY_EMAIL={email.strip()}",
        f"CORS_ORIGINS={cors}",
        "",
        f"JWT_SECRET={jwt}",
        f"ADMIN_API_KEY={admin}",
        "POSTGRES_USER=raguser",
        f"POSTGRES_PASSWORD={postgres_password}",
        "POSTGRES_DB=ragdb",
        "PUBLIC_SIGNUP_ENABLED=" + signup,
        "ALLOW_PUBLIC_SIGNUP_IN_PRODUCTION=" + allow_signup,
        "",
        f"GROQ_API_KEY={groq_key.strip()}",
        f"COHERE_API_KEY={cohere_key.strip()}",
        "",
        "API_KEYS=",
        "PROMPT_PACK_ID=default",
        "RAG_PERSONA=",
        "RATE_LIMIT_PER_MINUTE=30",
        "MAX_QUERY_CHARS=2000",
        "WEB_HTTP_PORT=80",
        "WEB_HTTPS_PORT=443",
        "",
        "QDRANT_COLLECTION_NAME=finance_documents_v1",
        "RERANK_MIN_SCORE=0.30",
        "SEMANTIC_CACHE_ENABLED=true",
        "LOG_LEVEL=INFO",
        "LOG_JSON=true",
        "",
        "# DATABASE_URL is injected by docker-compose from POSTGRES_* for containers.",
        "DATABASE_URL=",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate production .env for public HTTPS deploy.")
    parser.add_argument("--domain", required=True, help="Public hostname, e.g. app.example.com")
    parser.add_argument("--email", required=True, help="Let's Encrypt contact email")
    parser.add_argument("--groq-key", default="", help="Groq API key (or edit .env after)")
    parser.add_argument("--cohere-key", default="", help="Cohere API key (or edit .env after)")
    parser.add_argument(
        "--saas",
        action="store_true",
        help="Enable self-service signup (sets PUBLIC_SIGNUP_ENABLED and ALLOW_PUBLIC_SIGNUP_IN_PRODUCTION)",
    )
    parser.add_argument("--out", type=Path, default=ROOT / ".env", help="Output path (default: .env)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing output file")
    args = parser.parse_args()

    if args.out.exists() and not args.force:
        print(f"ERROR: {args.out} already exists. Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    password = _token(24)
    text = build_env_text(
        domain=args.domain,
        email=args.email,
        groq_key=args.groq_key,
        cohere_key=args.cohere_key,
        saas_signup=args.saas,
        postgres_password=password,
    )
    args.out.write_text(text, encoding="utf-8")
    print(f"Wrote {args.out}")
    print()
    print("Next steps:")
    print("  1. Point DNS A/AAAA for", args.domain.strip(), "to this server.")
    print("  2. Open firewall ports 80 and 443.")
    if not args.groq_key or not args.cohere_key:
        print("  3. Edit .env and set GROQ_API_KEY and COHERE_API_KEY if not passed.")
    print("  4. python scripts/verify_production_env.py")
    print("  5. docker compose up -d --build")
    print("  6. docker compose --profile tools up -d worker   # PDF uploads")
    print("  7. python scripts/manage_tenants.py create --id my-org --name 'My Org'")
    print(f"  8. curl -fsS https://{args.domain.strip().lower()}/api/health/ready")


if __name__ == "__main__":
    main()
